### ISSUE TITLE
31.03.2020 Peer-to-peer Code Review

### ISSUE THREAD

**Issue by sebGilR** [shubham14p3/Online-shop-for-electronics#2]
During our morning review we gathered the following feedback:

- Improving the naming structure.
- Re-use of classes is really good, however, when there are elements that share common characteristics (all children of the same container or all with a class that begins with "xyz-..." targetting them with one selector in common instead of adding multiple classes to all of them can reduce the code in HTML, making it cleaner.
- Declare flex only in one of the classes used for each item.
- Fix the centering of arrow icons when hovered.

**Comment by shubham14p3** [comment]
Thank you @sebGilR for your wonderful feedback.
Will make sure to keep the points checked in my future projects as way of improvement.
